language: node_js
before_install: if [[ `npm -v` != 6.14.8 ]]; then npm i -g npm@6.14.8; fi
node_js:
- 'lts/*'
cache:
  directories:
  - node_modules
sudo: false
script: npm test
after_script:
- npm run coverage
- cat ./coverage/lcov.info | coveralls
